apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: priority-attendance
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: priority-attendance

